In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_path = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing' + '/'
data_pathlist = os.listdir(data_path)

v = ''
for i in data_pathlist:
    v += f"path_{i.split('.')[0]} = '{data_path + i}'\n{i.split('.')[0]} = pd.read_csv(path_{i.split('.')[0]})\n\n"
print(v)

path_test = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/test.csv'
test = pd.read_csv(path_test)

path_sample_submission = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/sample_submission.csv'
sample_submission = pd.read_csv(path_sample_submission)

path_train = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/train.csv'
train = pd.read_csv(path_train)

In [5]:
path_test = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/test.csv'
test = pd.read_csv(path_test)

path_sample_submission = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/sample_submission.csv'
sample_submission = pd.read_csv(path_sample_submission)

path_train = '/home/sjt/space/github/kaggle/data/mercedes_benz_greener_manufacturing/train.csv'
train = pd.read_csv(path_train)
train_y = train.pop('y')

In [6]:
train

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,k,v,at,a,d,u,j,o,0,...,0,0,1,0,0,0,0,0,0,0
1,6,k,t,av,e,d,y,l,o,0,...,1,0,0,0,0,0,0,0,0,0
2,7,az,w,n,c,d,x,j,x,0,...,0,0,0,0,0,0,1,0,0,0
3,9,az,t,n,f,d,x,l,e,0,...,0,0,0,0,0,0,0,0,0,0
4,13,az,v,n,f,d,h,d,n,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,ak,s,as,c,d,aa,d,q,0,...,1,0,0,0,0,0,0,0,0,0
4205,8406,j,o,t,d,d,aa,h,h,0,...,0,1,0,0,0,0,0,0,0,0
4206,8412,ak,v,r,a,d,aa,g,e,0,...,0,0,1,0,0,0,0,0,0,0
4207,8415,al,r,e,f,d,aa,l,u,0,...,0,0,0,0,0,0,0,0,0,0
4208,8417,z,r,ae,c,d,aa,g,w,0,...,1,0,0,0,0,0,0,0,0,0