In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_path = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting' + '/'
data_pathlist = os.listdir(data_path)

v = ''
for i in data_pathlist:
    v += f"path_{i.split('.')[0]} = '{data_path + i}'\n{i.split('.')[0]} = pd.read_csv(path_{i.split('.')[0]})\n\n"
print(v)

path_air_visit_data = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_visit_data.csv'
air_visit_data = pd.read_csv(path_air_visit_data)

path_date_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/date_info.csv'
date_info = pd.read_csv(path_date_info)

path_sample_submission = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/sample_submission.csv'
sample_submission = pd.read_csv(path_sample_submission)

path_store_id_relation = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/store_id_relation.csv'
store_id_relation = pd.read_csv(path_store_id_relation)

path_air_reserve = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_reserve.csv'
air_reserve = pd.read_csv(path_air_reserve)

path_hpg_reserve = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/hpg_reserve.csv'
hpg_reserve = pd.read_csv(path_hpg_reserve)

path_air_store_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_store_info.csv'
air_store_info = pd.read_csv(path_air_store_info)

path_hpg_store_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/hpg_store_info.csv'
hpg_store_info = pd.read_csv(path_hpg_store_info)

In [3]:
path_air_visit_data = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_visit_data.csv'
air_visit_data = pd.read_csv(path_air_visit_data)

path_date_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/date_info.csv'
date_info = pd.read_csv(path_date_info)

path_sample_submission = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/sample_submission.csv'
sample_submission = pd.read_csv(path_sample_submission)

path_store_id_relation = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/store_id_relation.csv'
store_id_relation = pd.read_csv(path_store_id_relation)

path_air_reserve = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_reserve.csv'
air_reserve = pd.read_csv(path_air_reserve)

path_hpg_reserve = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/hpg_reserve.csv'
hpg_reserve = pd.read_csv(path_hpg_reserve)

path_air_store_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/air_store_info.csv'
air_store_info = pd.read_csv(path_air_store_info)

path_hpg_store_info = '/home/sjt/space/github/kaggle/data/recruit_restaurant_visitor_forecasting/hpg_store_info.csv'
hpg_store_info = pd.read_csv(path_hpg_store_info)

In [4]:
air_visit_data

                air_store_id  visit_date  visitors
0       air_ba937bf13d40fb24  2016-01-13        25
1       air_ba937bf13d40fb24  2016-01-14        32
2       air_ba937bf13d40fb24  2016-01-15        29
3       air_ba937bf13d40fb24  2016-01-16        22
4       air_ba937bf13d40fb24  2016-01-18         6
...                      ...         ...       ...
252103  air_24e8414b9b07decb  2017-04-18         6
252104  air_24e8414b9b07decb  2017-04-19         6
252105  air_24e8414b9b07decb  2017-04-20         7
252106  air_24e8414b9b07decb  2017-04-21         8
252107  air_24e8414b9b07decb  2017-04-22         5

[252108 rows x 3 columns]